### ISSUE TITLE
Trouble Running on MacOS Mojave

### ISSUE THREAD

**Issue by Geekz45679** [linuxgurugamer/LaunchCountdownEx#11]
**Hey,**
I'm having trouble getting this mod to work on my Macbook Air.

**Here are my specifications:**
- **CPU:** Dual Core i5
- **RAM:** 4GB DDR3-1600
- **OS:** MacOS Mojave (10.4)
- **Game Version: 1.4.5**

Most mods seem to work just fine on my laptop, only this one seems to not want to work. I've made sure that I've gone through and used the 1.4 build, but that still wouldn't fix my issue.

Some troubleshooting tips would be appreciated, thanks!

**Comment by linuxgurugamer** [comment]
I'd prefer that support issues like this be done on the forum, so that others may be able to provide help as well as myself.
That being said, whenever asking for help like this, you should always provide a log file (preferably the output_log.txt), which contains lots of information which can be helpful in diagnosing the issue.

**Comment by Geekz45679** [comment]
Please disregard this, I hadn't installed the required dependencies.

May I suggest adding the dependencies due to the README.md, as I found this version of the mod by going to the curse page, the original repository for the **old** mod, then looking through the forks to find an updated version and came across this. Yes it was stupid of me to not find the forum link and check for dependencies, but at the same time you should save future people who may find themselves in this situation by adding the dependency links.

**Comment by linuxgurugamer** [comment]
I maintain over 165 mods.  All of my mods are available on GitHub and Spacedock, i do not support Curse.
I don't have time to track down all the old threads for all the mods.
Also, all of my mods are installable using CKAN, which takes care of the dependencies
