### ISSUE TITLE
NASA Countdown window disappears except for numbers.

### ISSUE THREAD

**Issue by GJNelson7030** [linuxgurugamer/LaunchCountdownEx#12]
Here is my KSP.log file...

[KSP.log](https://github.com/linuxgurugamer/LaunchCountdownEx/files/3898912/KSP.log)

**Comment by GJNelson7030** [comment]
After reviewing and thinning my mods used list, here is the new KSP.log file...

[KSP.log](https://github.com/linuxgurugamer/LaunchCountdownEx/files/3903685/KSP.log)

**Comment by linuxgurugamer** [comment]
Fixed
