### ISSUE TITLE
[bug] unchecked Gravity Turn

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/LaunchCountdownEx#7]
Maybe there is some other mod interfere, but if I uncheck Gravity Turn, then it still starts

**Comment by linuxgurugamer** [comment]
Had you previously used it with Gravity Turn in the same game?

**Comment by yalov** [comment]
I think yes, I was trying it, then it hasn't GT-support.

**Comment by linuxgurugamer** [comment]
I found the problem

**Comment by yalov** [comment]
Now I have unchecked GT, and empty launch sequence — it does nothing. 
Should it launch last stage at 0:00, or I need manually set staging?

**Comment by yalov** [comment]
The `sound enabled` checkbox doesn't "enabled" any sound, 
it allows sound package to init a start countdown value. 
The disabled `sound enabled` checkbox sets start countdown value to 15s.

`limit to 15s` and revert checkbox then?

**Comment by linuxgurugamer** [comment]
Regarding the unchecked GT and empty launch sequence, it is behaving properly.  It does what you tell it to do, if you don't tell it to launch, it just looks and sounds pretty.
Post the sound_enabled in a separate issue, please.
This bug was fixed earlier
